name: Deploy backend to Azure Web App

on:
  push:
    branches:
      - zk_main
  workflow_dispatch:

env:
  AZURE_WEBAPP_PACKAGE_PATH: backend

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id:     ${{ secrets.AZUREAPPSERVICE_CLIENTID_… }}
          tenant-id:     ${{ secrets.AZUREAPPSERVICE_TENANTID_… }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_… }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: cpsc49200capstonebackend
          slot-name: Production
          package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
